### ISSUE TITLE
Why is the camera fps greater than 30fps?

### ISSUE THREAD

**Issue by howyoungchen** [Qengineering/YoloFastest-ncnn-Jetson-Nano#2]
I changed the input of the model to a camera with a maximum input of 30 frames per second.
And changed the position of the line of code that starts timing to below the beginning of the while loop.
But the camera fps greater than 30fps?
Looking forward to your early reply.

**Comment by Qengineering** [comment]
There are two possible reasons.

1. We use the simple cv::capture to get frames from the camera. More accurate is a pipeline with GStreamer.
2. The FPS shown represents the time a frame is analyzed, not the camera's actual FPS. We use this method because grabbing frames and other (sometimes time-consuming) pre- and post-image manipulation will lower the FPS and not the inference time. Change the code if you want to get the actual FPS. 
```

        Tbegin = std::chrono::steady_clock::now();

        std::vector<TargetBox> boxes;
        yoloF2.detection(frame, boxes);
        draw_objects(frame, boxes);
        Tend = std::chrono::steady_clock::now();

        //calculate frame rate
        f = std::chrono::duration_cast <std::chrono::milliseconds> (Tend - Tbegin).count();
```
to
```
        std::vector<TargetBox> boxes;
        yoloF2.detection(frame, boxes);
        draw_objects(frame, boxes);
 
        Tend = std::chrono::steady_clock::now();
        //calculate frame rate
        f = std::chrono::duration_cast <std::chrono::milliseconds> (Tend - Tbegin).count();
        Tbegin = Tend;

```
